# This configuration is good for testing locally. It is not suited for
# production environments for the following reasons:
#
# 1. No persistent storage
# 2. Admin interface is not secured
# 3. Endpoint does not reflect a production endpoint
# 4. "Open mediation," or granting all incoming mediation requests, is enabled

# General
label: Mediator
endpoint: http://localhost:3000
inbound-transport:
  - [http, 0.0.0.0, 3000]
outbound-transport: http

# Mediator does not use a ledger
no-ledger: true

# Admin
admin: [0.0.0.0, 3001]
admin-insecure-mode: true

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true

# Create and print multi-use invitation
connections-invite: true
invite-multi-use: true

# Mediation
open-mediation: true
enable-undelivered-queue: true
